# app/image_tools.py
"""Image Generation Tool for Ripple - Foresight Angle using gemini-3.1-flash-lite-image."""

import hashlib
import json
import time
from google import genai
from google.genai import types
from google.cloud import storage
from google.adk.tools import ToolContext

BUCKET_NAME = "ripple-public-assets-qwiklabs-gcp-03-3773bdab8c6e"
PROJECT_ID = "qwiklabs-gcp-03-3773bdab8c6e"


async def generate_decision_item_image(
    item_description: str,
    tool_context: ToolContext = None,
) -> str:
    """Generates an image for a decision scenario item (e.g. '75lb Golden Retriever on 4th floor stairs')
    using gemini-3.1-flash-lite-image in the global region.

    Saves the generated image to Playground artifacts via tool_context.save_artifact,
    uploads the image bytes directly to public GCS storage, and returns the public https URL.

    Args:
        item_description: Description of the item or scenario to generate an image for.
        tool_context: Automatically injected ADK ToolContext for saving artifacts.

    Returns:
        JSON string containing the public Cloud Storage image URL and artifact metadata.
    """
    try:
        # Initialize GenAI Client in global region for gemini-3.1-flash-lite-image
        client = genai.Client(vertexai=True, location="global")

        prompt = f"High-quality 3D isometric representation of: {item_description}"
        response = client.models.generate_content(
            model="gemini-3.1-flash-lite-image",
            contents=prompt,
        )

        # Extract image bytes from generated response
        candidates = getattr(response, "candidates", [])
        if not candidates or not candidates[0].content.parts:
            return "Error: No image content generated by gemini-3.1-flash-lite-image."

        part = candidates[0].content.parts[0]
        if not part.inline_data or not part.inline_data.data:
            return "Error: Generated response did not contain inline image data."

        image_bytes = part.inline_data.data
        mime_type = part.inline_data.mime_type or "image/jpeg"

        # Unique filename
        hash_id = hashlib.md5(f"{item_description}{time.time()}".encode()).hexdigest()[:10]
        filename = f"decision_item_{hash_id}.jpg"

        # 1. Save artifact to ADK Playground Artifacts Panel if tool_context is provided
        if tool_context is not None:
            try:
                artifact_part = types.Part.from_bytes(data=image_bytes, mime_type=mime_type)
                await tool_context.save_artifact(
                    filename=filename,
                    artifact=artifact_part,
                    custom_metadata={"item_description": item_description, "model": "gemini-3.1-flash-lite-image"},
                )
            except Exception as art_err:
                print(f"Notice: artifact saving encountered error/notice: {art_err}")

        # 2. Upload image bytes directly to public GCS bucket (no local file written)
        storage_client = storage.Client(project=PROJECT_ID)
        bucket = storage_client.bucket(BUCKET_NAME)
        gcs_object_path = f"generated_items/{filename}"
        blob = bucket.blob(gcs_object_path)
        blob.upload_from_string(image_bytes, content_type=mime_type)

        public_url = f"https://storage.googleapis.com/{BUCKET_NAME}/{gcs_object_path}"

        result = {
            "item_description": item_description,
            "public_image_url": public_url,
            "artifact_filename": filename,
            "model_used": "gemini-3.1-flash-lite-image",
            "status": "Image generated successfully, saved to Playground artifacts, and uploaded to public GCS.",
        }

        return json.dumps(result, indent=2)
    except Exception as e:
        return f"Error generating decision item image: {str(e)}"
